# Generated by Django 6.0.7 on 2026-10-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(verbose_name='預測產生日期')),
                ('data_date', models.DateField(verbose_name='股價資料日期')),
                ('symbol', models.CharField(db_index=True, max_length=10, verbose_name='股票代號')),
                ('stock_name', models.CharField(blank=True, default='', max_length=100, verbose_name='股票名稱')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='預測基準收盤價')),
                ('predicted_return_20', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='預測20日報酬率（百分比）')),
                ('rank', models.PositiveIntegerField(verbose_name='當次排名')),
                ('model_version', models.CharField(default='V5.7-FORWARD', max_length=50, verbose_name='模型版本')),
                ('horizon', models.PositiveIntegerField(default=20, verbose_name='預測交易日數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='紀錄建立時間')),
            ],
            options={
                'verbose_name': 'AI 歷史預測',
                'verbose_name_plural': 'AI 歷史預測',
                'ordering': ['-created_at', 'rank'],
                'indexes': [models.Index(fields=['prediction_date', 'symbol'], name='pred_date_symbol_idx')],
            },
        ),
    ]
