# Generated by Django 6.0.7 on 2026-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_close_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='實際收盤價'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='實際報酬計算日期'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_return_20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='實際報酬率（百分比）'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='direction_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='漲跌方向是否預測正確'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='績效評估時間'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='prediction_error',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='預測誤差（百分點）'),
        ),
    ]
